apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

/*
helmGlobals:
  chartHome: string
  configHome: string
*/
helmCharts:
- name: prometheus
  version: string
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: 15.13.0
  namespace: prometheus
  valuesInline: map[string]interface{}
  valuesFile: values.yaml
  valuesMerge: false
  includeCRDs: true
