namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.5
  
generatorOptions:
 disableNameSuffixHash: false
 annotations:
   metallb.universe.tf/address-pool: 172.16.100.150-172.16.100.175
